keys:
  redmine:
    informea:
      url: https://support.informea.org
      api_key: YOUR_API_KEY
    helpdesk:
      url: https://helpdesk.eaudeweb.ro
      api_key: YOUR_API_KEY
  clockify:
    workspace_id: CLOCKIFY_WORKSPACE_ID

database:
  database_type: mysql
  database_name: redmineclockify
  username: root
  password: root
  server: localhost
  port: 3306
